name: Frontend Tests

on:
  pull_request:

jobs:
  check_paths:
    runs-on: ubuntu-latest
    outputs:
      should_run: ${{ steps.filter.outputs.backend }}
    steps:
      # These workflows are from the GitHub marketplace.
      - uses: actions/checkout@v4 # Official action for cloning the repository to the runner.
      - uses: dorny/paths-filter@v3.0.2 # Analyzises the code for changes.
        id: filter
        with:
          filters: |
            backend:
              - 'src/Frontend/**'
              - '.github/workflows/backend-tests.yaml'
  test:
    name: Test Frontend
    needs: check_paths
    if: ${{ needs.check_paths.outputs.should_run == 'true' }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src/backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install UV
        uses: astral-sh/setup-uv@v5

      - name: Set up Python
        run: uv python install

      - name: Install dependencies
        run: |
          uv sync --locked --dev

      - name: Lint with Ruff
        run: |
          uv run ruff check --output-format=github --target-version=py313 src tests
          uv run ruff format --diff --check --target-version=py313 src tests

      - name: Run tests with coverage
        run: |
          # '--cov' is targeting the whole directory, --cov-report creates the xml report,
          # --cov-fail won't let the test pass under 80% coverage
          # Coverage means the amout of code the test covers
          uv run pytest tests/ -v --cov=src/frontend --cov-report=xml --cov-fail-under=80

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: ./src/frontend/coverage.xml
          retention-days: 7
        if: ${{ always() }}

      - name: Coverage Report
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: ./src/frontend/coverage.xml
          badge: true
          format: markdown
          output: both

      - name: Add Coverage PR Comment
        uses: marocchino/sticky-pull-request-comment@v2
        if: github.event_name == 'pull_request'
        with:
          header: test-coverage
          recreate: true
          path: code-coverage-results.md
